name 'denyhost'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures denyhost'
long_description 'Installs/Configures denyhost'
version '0.1.0'
